<!DOCTYPE html>

<html lang="de">
  	<head>
  	
  		<!-- Header -->
	  	<?php include('_include/header.php'); ?>
	  	
  	</head>
  	<body>
  	
	  	<!-- Navigation -->
    	<?php include('_include/navigation.php'); ?>

    	<!-- Container -->
    	<div class="container"> 
	    	<div class="container-fluid">
		    	<div class="row-fluid">
		    	
		    		<!-- Sidebar  -->
			    	<div class="span3">
				    	<div class="sidebar-nav">
					    	<ul class="nav nav-list bs-docs-sidenav affix" id="sidebar">
						    	<li class="sidebar"><a href="#" class="legal">Legal notice</a></li>
						    	<li class="sidebar"><a href="#" class="links">Links to third party sites</a></li>
						    	<li class="sidebar"><a href="#" class="liability">Limitation of Liability</a></li>
					        </ul>
					    </div>
					</div><!-- Sidebar -->

					<!-- Content -->
					<div class="span9">
						<div class="post" id="legal">
							<h2>Legal notice</h2>
							<div class="entry">
								<p>The developers of this web site and of the SeaPal app do not assume any liability.</p>
							</div>
						</div>
						<div class="post" id="links">
							<br><br>
							<h2>Links to third party sites</h2>
							<div class="entry">
								<p>This Web site may contain links to web sites controlled by parties other than SeaPal. SeaPal is not responsible for and does not endorse or accept any responsibility for the contents or use of these third party web sites. SeaPal is providing these links to you only as a convenience, and the inclusion of any link does not imply endorsement by SeaPal of the linked web site. It is your responsibility to take precautions to ensure that whatever you select for your use is free of viruses or other items of a destructive nature.
								</p>
							</div>
						</div>
						<div class="post" id="lagal">
							<br><br>
							<h2>Google Analytics Disclaimer</h2>
							<div class="entry">
								<p>					
									This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States.
								</p> 
								<p>In case IP-anonymisation is activated on this website, your IP address will be truncated within the area of Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases the whole IP address will be first transfered to a Google server in the USA and truncated there. The IP-anonymisation is active on this website.
								</p> 
								<p>Google will use this information on behalf of the operator of this website for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing them other services relating to website activity and internet usage.
								</p> 
								<p>The IP-address, that your Browser conveys within the scope of Google Analytics, will not be associated with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this website. You can also opt-out from being tracked by Google Analytics with effect for the future by downloading and installing Google Analytics Opt-out Browser Addon for your current web browser: <a href="http://tools.google.com/dlpage/gaoptout?hl=en">http://tools.google.com/dlpage/gaoptout?hl=en</a>.
								</p>				
							</div>
						</div>			
						<div class="post" id="liability">
							<br><br>
							<h2>Limitation of Liability</h2>
							<div class="entry">
								<p>SeaPal SHALL NOT BE LIABLE FOR ANY DAMAGES SUFFERED AS A RESULT OF USING, MODIFYING, CONTRIBUTING, COPYING, DISTRIBUTING, OR DOWNLOADING THE MATERIALS. IN NO EVENT SHALL SeaPal BE LIABLE FOR ANY INDIRECT, PUNITIVE, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGE (INCLUDING BUT NOT LIMITED TO LOSS OF BUSINESS, REVENUE, PROFITS, USE, DATA OR OTHER ECONOMIC ADVANTAGE), HOWEVER IT ARISES, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF INFORMATION AVAILABLE FROM THIS WEB SITE, EVEN IF SeaPal HAS BEEN PREVIOUSLY ADVISED OF THE POSSIBILITY OF SUCH DAMAGE. YOU HAVE SOLE RESPONSIBILITY FOR THE ADEQUATE PROTECTION AND BACKUP OF DATA AND/OR EQUIPMENT USED IN CONNECTION WITH THE WEB SITE AND YOU WILL NOT MAKE A CLAIM AGAINST SeaPal FOR LOST DATA, RE-RUN TIME, INACCURATE OUTPUT, WORK DELAYS, OR LOST PROFITS RESULTING FROM THE USE OF THE MATERIALS. YOU AGREE TO HOLD SeaPal HARMLESS FROM, AND YOU COVENANT NOT TO SUE SeaPal FOR, ANY CLAIMS BASED ON OR RELATED TO THE USE OF THE WEB SITE.
								</p>
								<br><br>
							</div>
						</div>
					</div><!-- Content -->
		
				</div>	
			</div>
    	</div><!-- Container -->

		<!-- Footer -->
		<?php include('_include/footer.php'); ?>

	    <!-- Java-Script -->
	    <script src="../js/bootstrap/bootstrap-transition.js"></script>
	    <script src="../js/bootstrap/bootstrap-button.js"></script>
	    <script src="../js/bootstrap/bootstrap-collapse.js"></script>
	    <script src="../js/bootstrap/bootstrap-affix.js"></script>

  </body>
</html>